### PR TITLE
Change Context variables: `fooId` => `foo`

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review. Especially `Channel`.

**Comment by tomaszdurka** [comment]
Ok, these changes made me think about non-id approach a bit.
Before we had:
```js
{channelId: 'channel-id', channelKey: 'channel-key'}
{channelId: 'channel-id'}
{sessionId: 'session-id'}
```
With new approach we gonna have:
```js
{channel: {id: 'channel-id', key: 'channel-key'}}
{channel: {id: 'channel-id'}}
{session: 'session-id'}
```
For me above means inconsistency and it's prone to errors.

I would stick to proposition one or this:
```js
{channel: {id: 'channel-id', key: 'channel-key'}}
{channel: {id: 'channel-id'}}
{session: {id: 'session-id'}
```


@njam @vogdb wdyt?

**Comment by vogdb** [comment]
> I would stick to proposition one

And what was the *proposition one* ?

**Comment by tomaszdurka** [comment]
How it was before.

**Comment by vogdb** [comment]
Ah, ok. I'm fine with both. On my taste this one is better

>
```js
{channel: {id: 'channel-id', key: 'channel-key'}}
{channel: {id: 'channel-id'}}
{session: {id: 'session-id'}
```

**Comment by tomaszdurka** [comment]
@njam please put your cents. 

I also understand that creating those objects seems pretty basic in js/nodejs, but could be challenge in other languages? :)

**Comment by njam** [comment]
- janus.sessionId
- janus.mediaId
- janus.channelKey

**Comment by vogdb** [comment]
So, do you choose to keep the existing solution or partially rename? Also I think that Tomasz made a very good note:

> I also understand that creating those objects seems pretty basic in js/nodejs, but could be challenge in other languages? :)

**Comment by tomaszdurka** [comment]
Done in https://github.com/cargomedia/cm-janus/pull/246

**Pull request closed without merging**
