### PR TITLE
Loggly Alert: cm-janus fatal error

### PR DESCRIPTION
**Pull request by vogdb**
https://cargomedia.loggly.com/search/?terms=tag%3Acm-janus+AND+json.level%3Afatal&source_group=&savedsearchid=206843&from=2016-04-27T13%3A49%3A38Z&until=2016-04-27T13%3A54%3A38Z

```
{"level":"fatal","message":"Unexpected rejection error.","exception":{"type":"Error","message":"This socket has been ended by the other party","stack":"Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:284:12)
    at Sender.frameAndSend (/usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:232:22)
    at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:126:12
    at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/PerMessageDeflate.js:313:5
    at afterWrite (_stream_writable.js:354:3)
    at onwrite (_stream_writable.js:345:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:623:5)"},"hostname":"janus2.fuckbook.com","timestamp":"2016-04-27T13:54:01+00:00"}
```

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Hmm ok I thought this happens when we try to send something within our existing resource. So that we can catch this in some catch block not unhandled one.

**Comment by vogdb** [comment]
@tomaszdurka please look

**Comment by tomaszdurka** [comment]
Looks good for me, @njam agree? :)

**Comment by njam** [comment]
Trust you on this.

**Pull request merged**
