### PR TITLE
Streamline job handling (logging, cleaning, etc)

### PR DESCRIPTION
**Pull request by tomaszdurka**
Depends on #153.

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Example thumbnail processing in log:
```
app info Processing Job{"id":"job-79acc23cc44b5007c2f5edf9128f05a7","name":"janus.plugin.cm.rtpbroadcast:thumbnailing-finished","workingDirectory":"/var/lib/cm-janus/jobs-temp-files/job-79acc23cc44b5007c2f5edf9128f05a7-1453079069242"}
app debug Starting job process: `mjr2png /var/lib/janus/recordings/thum-jfl4fmteNrxzYgcsx7IPAA__-30187191286-thumb.mjr 1920 540 /var/lib/cm-janus/jobs-temp-files/job-79acc23cc44b5007c2f5edf9128f05a7-1453079069242/tmp-24521lPHD7XYf3IDZ.png || test "69" = "$?"`
app debug Running cm command `bin/cm media-streams import-video-thumbnail 235fc5ea145aab6765def5a61c7a0807 /var/lib/cm-janus/jobs-temp-files/job-79acc23cc44b5007c2f5edf9128f05a7-1453079069242/tmp-24521lPHD7XYf3IDZ.png`
```

**Comment by tomaszdurka** [comment]
Example audio archive job:
```
app info Processing Job{"id":"job-58183b87a49458e09315a0bcc770f283","name":"janus.plugin.cm.audioroom:archive-finished","workingDirectory":"/var/lib/cm-janus/jobs-temp-files/job-58183b87a49458e09315a0bcc770f283-1453081607680"}
app debug Starting job process: `lame /var/lib/janus/recordings/rec-o9H45TXrfDmOOqitLJxg2g__-32689476787-audioroom.wav /var/lib/cm-janus/jobs-temp-files/job-58183b87a49458e09315a0bcc770f283-1453081607680/tmp-29568JDytGrx6aKJM.mp3`
app debug Running cm command `bin/cm media-streams import-archive 19eb7348860120fb31681ab9e2a86d46 /var/lib/cm-janus/jobs-temp-files/job-58183b87a49458e09315a0bcc770f283-1453081607680/tmp-29568JDytGrx6aKJM.mp3`
app info Removing /var/lib/janus/jobs/job-58183b87a49458e09315a0bcc770f283.json
```

**Comment by tomaszdurka** [comment]
Example video archive job:
```
app info Processing Job{"id":"job-a6bd07ccca424a454553af68f1c3b4eb","name":"janus.plugin.cm.rtpbroadcast:archive-finished","workingDirectory":"/var/lib/cm-janus/jobs-temp-files/job-a6bd07ccca424a454553af68f1c3b4eb-1453081783044"}
app debug Starting job process: `mjr2webm /var/lib/janus/recordings/rec-cnnKZSJAoz78UJxlpd4pxA__-32246095955-video.mjr /var/lib/janus/recordings/rec-cnnKZSJAoz78UJxlpd4pxA__-32246095700-audio.mjr /var/lib/cm-janus/jobs-temp-files/job-a6bd07ccca424a454553af68f1c3b4eb-1453081783044/tmp-29568f1Jhh2XV4Hji.webm`
app debug Running cm command `bin/cm media-streams import-archive 58c700586de2ba1c24f669c5342114d9 /var/lib/cm-janus/jobs-temp-files/job-a6bd07ccca424a454553af68f1c3b4eb-1453081783044/tmp-29568f1Jhh2XV4Hji.webm`
app info Removing /var/lib/janus/jobs/job-a6bd07ccca424a454553af68f1c3b4eb.json
```

**Comment by tomaszdurka** [comment]
@vogdb please review after #153

**Comment by vogdb** [comment]
starting

**Comment by vogdb** [comment]
fixing tests

**Comment by vogdb** [comment]
@tomaszdurka lgtm if you agree

**Pull request merged**
