### PR TITLE
Add timestamps to log

### PR DESCRIPTION
**Pull request by vogdb**
@vogdb something for you?

cc @tomaszdurka

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Postponed review for moment.

**Comment by tomaszdurka** [comment]
@vogdb I would like to discuss whole logging topic. I think it's really important and possibly not only because of library choice.

Ping me on hipchat.

**Comment by vogdb** [comment]
@tomaszdurka ?

**Comment by tomaszdurka** [comment]
lg

**Pull request merged**
