### PR TITLE
Gentle shutdown of http-server

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
@vogdb  please review. it's very basic and waits for current connections.
There is no way  (at least I didn't find them ) to gracefully finish a connection (to send some another response)  on server shutdown.
We either wait for it normal dispatching or silently terminate it

**Comment by vogdb** [comment]
Please consider the error case in callback of `close`

**Comment by fvovan** [comment]
it's done

**Comment by vogdb** [comment]
- pass `err` to reject
- log level for minor failure should be higher than `info`. `warn`?

**Comment by fvovan** [comment]
I would use `error` then

**Comment by vogdb** [comment]
lgtm

**Comment by fvovan** [comment]
then could be merged after https://github.com/cargomedia/cm-janus/pull/81

**Comment by vogdb** [comment]
We can drop it, not crucial to have.

**Pull request closed without merging**
