### PR TITLE
Zombie audio publishers in status?

### PR DESCRIPTION
**Pull request by vogdb**
After some testing, where usually a `rpc_subscribe()` call would disallow subscribing, we ended up with lots of "zombie" audio publishers. Those were not connected anymore to cm-janus. Restarting janus and cm-janus removed them through syncing.
screen shot 2015-12-16 at 18 06 13

@tomaszdurka how does this status work? Is it proxied to janus, or it keeps its own state?
What could cause this?

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please look. Also I think that it would be more correct to create stream for audio plugin only after `configure event`. Like this:
```js
/**
 * @param {Object} message
 * @returns {Promise}
 */
PluginAudio.prototype.processMessage = function(message) {
  var janusMessage = message['janus'];

  if ('message' === janusMessage && 'configure' === message['body']['request']) {
    return this.onConfigure(message);
  }

  return PluginAudio.super_.prototype.processMessage.call(this, message);
};

/**
 * @param {Object} message
 * @returns {Promise}
 */
PluginAudio.prototype.onConfigure = function(message) {
  if (message['jsep'] && 'offer' == message['jsep']['type']) {
    var plugin = this;
    this.session.connection.transactions.add(message['transaction'], function(response) {
      if (plugin._isSuccessResponse(response)) {
        plugin.stream = Stream.generate(response['plugindata']['data']['id'], plugin);
        serviceLocator.get('logger').info('Added ' + plugin.stream + ' for ' + plugin);
      }
      return Promise.resolve(response);
    });
  }
  return Promise.resolve(message);
};
```

**Comment by vogdb** [comment]
As discussed we only subscribe in audio on webrtcup and we create stream on Join.

**Comment by vogdb** [comment]
It seems that I already implemented in the way that we want. @tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Ah true. So we just removed the publish from create.

**Comment by vogdb** [comment]
@tomaszdurka so what is your final resolution here?

**Comment by tomaszdurka** [comment]
lgtm

**Comment by tomaszdurka** [comment]
But remember this depends on https://github.com/cargomedia/cm/issues/2029, at least before releasing it.

**Comment by tomaszdurka** [comment]
@vogdb let's add #115 here.

**Comment by tomaszdurka** [comment]
@vogdb please review last commit.

@zazabe please adjust all `watch`, `join`, `switch` requests to include `['body']['channel_data']`.

**Comment by vogdb** [comment]
lgtm

**Comment by vogdb** [comment]
hmm cargomedia/cm#2029 wasn't yet merged.

**Comment by tomaszdurka** [comment]
Yes, this still needs a release - I thnk we can set it up all now.

**Pull request merged**
