### PR TITLE
Detach of Streaming plugin during the actual streaming kills the proxy

### PR DESCRIPTION
**Pull request by fvovan**
How to model: Open `streamingtest.html` -> Watch any stream -> Click **Stop** button (see the picture).

screen shot 2015-10-29 at 18 08 16

@fvovan @tomaszdurka FYI

### CODE REVIEW

**Comment by fvovan** [comment]
@vogdb please review.

**Comment by vogdb** [comment]
It's fine for now but we should fix the root of this. We need to intercept any break in both (janus and browser) connections and shutdown/reconnect appropriately.
@tomaszdurka your thoughts?

**Comment by fvovan** [comment]
we can close Janus side WS connection when receive 'close' on Browser's one.

**Comment by vogdb** [comment]
We are already doing it =) It just does not work because the closing of connection is not immediate =(
Please add me as collaborator to your fork of cm-janus

**Comment by fvovan** [comment]
Ah true, i mixed it with JanusConnection. 
You are added

**Comment by vogdb** [comment]
Thanks! The fix was a one-liner. @c949cc0ef48dcfca41bda68094fb00e5adedad95 shouldn't be needed.

**Comment by vogdb** [comment]
@fvovan please verify

**Comment by fvovan** [comment]
@vogdb , thanks,  it works
Shall I delete WS status checking or leave it?

**Comment by vogdb** [comment]
I guess it's not needed but I like the idea of verifying that connection is open, we can improve the queue mechanism and possibly to queue those `dead letters`.

**Pull request merged**
