### PR TITLE
Include "retryCount" in job processing error

### PR DESCRIPTION
**Pull request by vogdb**
For alerting it would be nice if we could include the number of retries a job was tried in the log entry "Failed job process".

@vogdb wdyt, can it be easily added?

cc @kris-lab @tomaszdurka

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by kris-lab** [comment]
@zazabe can we release this soon?

**Comment by zazabe** [comment]
lgtm

**Comment by njam** [comment]
@vogdb can you release a new version with this and let me know once done? thanks.

**Comment by njam** [comment]
@tomaszdurka could you take over here and release this?

**Comment by vogdb** [comment]
@njam FYI

**Comment by tomaszdurka** [comment]
I understand this has been already released. @vogdb right?

**Comment by vogdb** [comment]
yes

**Comment by tomaszdurka** [comment]
thanks

**Pull request merged**
