### PR TITLE
Make config system a la pulsar-api

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
@tomaszdurka , @vogdb  could you review it please
It affected logger as we need to pass Config instance downside.
If it's okay I will adjust our WS server to use it.

**Comment by vogdb** [comment]
Very good job! Ideally it would be nice to have the API of the previous module `config` that could be accessed by `require('config').get('propertyName')` + the ability to specify the filepath for it manually through the command line argument.

@tomaszdurka wdyt?

**Comment by fvovan** [comment]
But it has the ability to specify config path. I just moved it to bin/cm-janus file. It's more proper place imo.

**Comment by vogdb** [comment]
You mean that the the previous module `config` had the ability to specify the config path? Cause I saw that it could specify only the config directory and names of files are not subjects to change.

**Comment by fvovan** [comment]
Nono, I meant 'pulsar-style config.
```
var argv = minimist(process.argv.slice(2));
var configPath = argv.c || __dirname + '/config.yaml';
```
But actually  'node-config' loaded filename could be adjusted via `NODE_ENV` env var and used together with `NODE_CONFIG` dir option it can specify full path.

**Comment by tomaszdurka** [comment]
@fvovan please take a look again and merge if ok.

**Pull request merged**
