### PR TITLE
Define message interpreters

### PR DESCRIPTION
**Pull request by vogdb**
### Browser -> cm-janus
We should deny illegal actions/plugins.
We should instantiate handler per plugin and attach listener to specific `handleId` at that time. We should store it per connection.
- `Streaming`
  - `{"request":"watch"}` holds the stream id. 
- `AudioBridge`
  - ?

### Janus -> cm-janus
In particular, for each handle involving a PeerConnection Janus provides notifications about its current state. To do so, the following events may be received as well:

- `webrtcup`: ICE and DTLS succeeded, and so Janus correctly established a PeerConnection with the user/application;
  - trigger `onSubscribe`, `onPublish` events
- `media`: whether Janus is receiving (receiving: true/false) audio/video (type: "audio/video") on this PeerConnection;
- `hangup`: the PeerConnection was closed, either by Janus or by the user/application, and as such cannot be used anymore.
  - trigger `onUnSubscribe`, `onUnPublish` events

Above events could be intercepted and its data passed to cm applications via rpc calls.

### CODE REVIEW

**Comment by vogdb** [comment]
I'm waiting here for #10.

**Comment by fvovan** [comment]
actually it's done (though all methods are just stubs ) but question about config is still open.

**Comment by vogdb** [comment]
Yes, I understand)

**Comment by tomaszdurka** [comment]
Closing in favor of #12.
@vogdb please reopen if disagree. Thanks.

**Pull request closed without merging**
