### PR TITLE
Throttle jobs

### PR DESCRIPTION
**Pull request by tomaszdurka**
If many jobs are retried, they all start at the same time. This can kill any machine.

@tomaszdurka @vogdb 
Should we throttle job execution by let's say max. 10 at the same time?

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb can you make a brief look about general idea?

**Comment by vogdb** [comment]
Looks ok
- `this._jobsDirectory = jobDirectory;` be consistent here. `job` or `jobs`?
- `processJob` to `handleJob`?

**Comment by tomaszdurka** [comment]
@vogdb please review library changes (tests will fail).

**Comment by vogdb** [comment]
@tomaszdurka wdyt about changing `JobFileProcessor` to `JobFileListener` ? So, instead of
```js
  this._processor  = new JobProcessor(tempFilesDir);
  this._fileProcessor = new JobFileProcessor(this._processor, jobDirectory);
```

you have this
```js
  var manager = this;
  this._jobFileListener = new JobFileListener(jobDirectory);
  this._jobFileListener.on('job', function(jobFilePath, jobDescription) {
    var jobId = path.basename(jobFilePath, '.json');
    var handler = manager.handlerRegistry.get(jobDescription['plugin'], jobDescription['event']);
    var job = handler.instantiateJob(jobId, jobDescription['data']);
    return manager._processor.processUntilSuccessful(job);
  });
```

**Comment by vogdb** [comment]
All job files that already exist will be emitted too by this listener

**Comment by tomaszdurka** [comment]
So for me it either should process job-files internally as in current-code solution or...
JobFileListener should evolve to more like FileListener and simply trigger event on each file - aka wrapper on top of inotify. Ending up as:
```
var manager = this;
  var processFile = function(file) {
    var jobDescription = manager.readFile(file);
    var jobId = path.basename(jobFilePath, '.json');
    var handler = manager.handlerRegistry.get(jobDescription['plugin'], jobDescription['event']);
    var job = handler.instantiateJob(jobId, jobDescription['data']);
    manager._processor.processUntilSuccessful(job);
    fs.unlink(file);
  };
  this._fileListener = new FileListener(jobDirectory);
  this._fileListener.readFiles().each(processFile);
  this._fileListener.listen(processFile);
```

I am not sure if it simplifies things.

**Comment by vogdb** [comment]
I see you don't like FileListener. Lets use your original approach.

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by tomaszdurka** [comment]
Still tests not adjusted.

**Comment by vogdb** [comment]
The idea looks good

**Comment by vogdb** [comment]
retaking the issue

**Comment by vogdb** [comment]
@tomaszdurka please review.
I used a not documented API of `async` 
```js
JobProcessor.prototype.stop = function() {
  //.....
    _.each(this._queue.tasks, function(task) {
```

`queue.tasks` is not documented API of `async.queue`. If we don't use it then we have to duplicate a tasks container on JobProcessor. I didn't want to duplicate.

**Comment by tomaszdurka** [comment]
Looks good!

**Pull request merged**
