### PR TITLE
Add token/secret to HttpServer handlers and CMApiClient requests

### PR DESCRIPTION
**Pull request by fvovan**
- Consider using the same `apiKey` for `HttpServer` and `CMApiClient`
- Use header for `HttpServer` `apiKey` authentication
- Send `apiKey` as first param in all `CMApiClient` `requests`
Example
```js
{
    method: 'CM_Janus_RpcEndpoints.publish',
    params: ['apiKey', 'streamKey', '...']
}
```
For other signatures check https://github.com/tomaszdurka/CM/blob/issue-1965/library/CM/Janus/RpcEndpoints.php

### CODE REVIEW

**Comment by fvovan** [comment]
@vogdb or @tomaszdurka  please review,
I'm not sure about https://github.com/cargomedia/cm-janus/commit/7c64642368e2d18e74d16e1ebc670c98c9f0c306 . It is valid practice to export instances instead classes?

**Comment by vogdb** [comment]
- `incomingApiKey` -> `apiKey`
- `'Api-Key'`. Do we really have such an odd auth headers from CM? Why not `api-key`?

**Comment by fvovan** [comment]
> 'Api-Key'. Do we really have such an odd auth headers from CM? Why not api-key?

It's just non formal convention to use Uppercase. Earlie all custom headers were obliged to have X- prefix but now it's deprecated

**Comment by vogdb** [comment]
> It's just non formal convention to use Uppercase. Earlie all custom headers were obliged to have X- prefix but now it's deprecated

ok then. Didn't know about it.

**Comment by vogdb** [comment]
- Also this one `incomingApiKey === undefined` to `!incomingApiKey`

**Comment by vogdb** [comment]
lgtm

**Comment by vogdb** [comment]
lets wait also for Tomasz's notes

**Comment by vogdb** [comment]
Hm. No Tomasz's notes. Merging then.

**Pull request merged**
