### PR TITLE
Context for logging

### PR DESCRIPTION
**Pull request by tomaszdurka**
Enrich and store context on these levels:

### Proxy/httpServer
1. Connection
 - id
 - arbitary data
2. Session
 - id
3. Plugin
 - id
4. Stream
 - id
 - channelMediaId
 - channelKey

### JobManager
1. Job
 - jobId
 - handler type (e.g. `janus.plugin.cm.audioroom:archive-finished`)
 - uid

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please look

**Comment by vogdb** [comment]
Wow. ok

**Comment by vogdb** [comment]
Two questions for the start:
- Why JanusConnection has context as a field property and as an argument in the method `JanusConnection.prototype.processMessage`? It also passes it to `this.getSession(sessionId).processMessage(message, context)` but `Session.prototype.processMessage = function(message)` does not accept `context`.
- Such structures are highly dangerous `Promise.resolve([response, context])`. Better `Promise.resolve({response: response, context: context})`.

**Comment by tomaszdurka** [comment]
Unfortunately I committed some discussion code - these are the questions you have.

**Comment by tomaszdurka** [comment]
Closing in favor #236

**Pull request closed without merging**
