### PR TITLE
Implement Connection object

### PR DESCRIPTION
**Pull request by tomaszdurka**
Holds:
- browserConnection
- janusConnection
- sessionId (token?)
- ~~clientKey (websocketConnection or unqiuely generated identifier)~~
- ~~streamName (streamId or roomName) - set later from message handlers (https://github.com/cargomedia/cm-janus/issues/8: watch event, etc.)~~ will be moved to Stream class

//discuss
- isWaitingForPlugin()
- waitPlugin(transactionId, pluginName)
- getPlugin(pluginName)
- setupPlugin(transactionId, pluginName, pluginId)

rather
// attachPlugin
// detachPlugin
// eventEmitter

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@fvovan can you review two latest commits:
- https://github.com/tomaszdurka/cm-janus/commit/2d1ece8e8bce06a2ace47e700597e8c59e4770be
- https://github.com/tomaszdurka/cm-janus/commit/863a661d0da6c18c50ec5284aaec9951c5973ab6

They are about adjust logger, plus moving config files into bin directory (not entirely sure about it though).

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by fvovan** [comment]
Not sure about moving configs to `bin/`. On *nix i would expect only executable files inside it.

**Comment by vogdb** [comment]
ok. The main concept is fine. We just need to complete all the gaps now.

**Comment by tomaszdurka** [comment]
Paired reviewed with @fvovan and @vogdb.

**Pull request merged**
