### PR TITLE
Do not send stdout/stderr on failedRepeatedly exceptions

### PR DESCRIPTION
**Pull request by vogdb**
just to be sure, we log every time, but we add stdout/stdeer every Xth time? or we log nothing or everything every Xth time?

I would log nothing and everything every Xth time

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Looks good!

**Comment by njam** [comment]
I understand the business logic is now:
- Only log every 10th trial (0, 10, 20, …)
- Whenever something is logged then `failedRepeatedly` is set

Did I interpret that correct?
If so, then I don't think this is what we want.

I would suggest:
- Log every incident
- Add `failedRepeatedly` at/after the 10th trial
- Add command output only the first trial

**Comment by vogdb** [comment]
> Did I interpret that correct?

How it works now
- log every incident as a warning without command output
- Log incident as an error with command output every 10x times.

**Pull request merged**
