### PR TITLE
Remove streams in cm on shutdown/startup

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka should I review here?

**Comment by tomaszdurka** [comment]
Not much to review yet

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
starting

**Comment by vogdb** [comment]
@tomaszdurka lgtm. Check my changes too

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
