### PR TITLE
implement Janus proxy

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb can you take a look?

@kris-lab or @njam what should happen to connections which are invalid (not authenticated)? 
Shall we close them (connections with browser and/or connections with janus)?
Thanks.

**Comment by vogdb** [comment]
seems fine for now

**Comment by njam** [comment]
I think closing is fine!

**Comment by tomaszdurka** [comment]
Agreed with @vogdb @fvovan to merge.

**Pull request merged**
