### PR TITLE
Loggly Alert: cm-janus fatal error

### PR DESCRIPTION
**Pull request by vogdb**
https://cargomedia.loggly.com/search/?terms=tag%3Acm-janus+AND+json.level%3Afatal&source_group=&savedsearchid=206843&from=2016-04-30T14%3A47%3A32Z&until=2016-04-30T14%3A52%3A32Z

```
{"level":"fatal","message":"Unexpected rejection error.","exception":{"type":"Error","message":"This socket has been ended by the other party","stack":"Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:284:12)
    at Sender.frameAndSend (/usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:232:22)
    at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:126:12
    at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/PerMessageDeflate.js:313:5
    at afterWrite (_stream_writable.js:354:3)
    at onwrite (_stream_writable.js:345:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:623:5)"},"hostname":"janus2.fuckbook.com","timestamp":"2016-04-30T14:50:46+00:00"}
```

### CODE REVIEW

**Comment by vogdb** [comment]
Ok. I did the text search for `send`. This is the last place where we send without `catch`. If it does not help then I don't know what will help.

@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Hmm, so now open will succeed (resolve), but internally fail?

**Comment by vogdb** [comment]
I don't know but this is the only place where `send` Promise is not caught.

**Comment by tomaszdurka** [comment]
Sorry, my bad, it's `send` not `open`... so now it won't resolve. Probably will timeout?

**Comment by vogdb** [comment]
You are right. We better reject there. @tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Hmm, but isn't this exactly the same as before your changes? Only difference we catch and rethrow?
Maybe we should just rethrow it as some known janus-error? So it's intercepted on outer level?

**Comment by vogdb** [comment]
This example should resolve your doubts.
```js
var Promise = require('bluebird');

new Promise(function(resolve, reject) {
  Promise.resolve().then(function() {
    throw new Error('I am an unhandled rejection');
  }).then(resolve);
}).catch(function(err) {
  console.log('Caught the unhandled', err);
});

new Promise(function(resolve, reject) {
  Promise.resolve().then(function() {
    throw new Error('I am a handled rejection');
  }).then(resolve).catch(reject);
}).catch(function(err) {
  console.log('Caught the handled', err);
});
```

The manually rejected `_queue` will be caught by the upper levels.

**Comment by tomaszdurka** [comment]
Oh yes, sure. I written some hidden code in my minda that we return this promise. I think i'm still in night-phase.
 
lgtm

**Pull request merged**
