### PR TITLE
Adjust config and split api keys.

### PR DESCRIPTION
**Pull request by fvovan**
Move proxy details to config and create split API keys for http-server  and cm-api-client

### CODE REVIEW

**Comment by fvovan** [comment]
@tomaszdurka  please review
so I renamed it to apiKey back but it will leave as 'serverKey' at CM's section.

**Comment by tomaszdurka** [comment]
Looks ok I guess... we are so inconsistent in terms of how we pass params to classes.

**Comment by fvovan** [comment]
hmm. do you mean that sometimes we cast config values but sometimes not and also we validate only few constructor arguments?

**Comment by tomaszdurka** [comment]
Yes, it's about constructors, but let's make it in another issue.

**Pull request merged**
