### PR TITLE
Cannot read property 'error' of undefined

### PR DESCRIPTION
**Pull request by vogdb**
I guess this should not happen?
```
TypeError: Cannot read property 'error' of undefined
    at /usr/lib/node_modules/cm-janus/lib/cm-api-client.js:50:27
    at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

### CODE REVIEW

**Comment by vogdb** [comment]
> Let's check if request-promise throws if there's no json response? Otherwise parse JSON manually?

@njam Lets just check for expected format of response?
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
@vogdb by "Let's check" we meant to check how it works, not necessary check in-code that :panda_face:

**Comment by vogdb** [comment]
@tomaszdurka so, shall we skip those changes?

**Comment by tomaszdurka** [comment]
lgtm_1_preview_featured

**Pull request merged**
