### PR TITLE
Queue streams methods per plugin

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
starting, will fix the tests on my own

**Comment by vogdb** [comment]
@tomaszdurka lgtm. You can check my changes.

**Comment by vogdb** [comment]
I will resolve the conflicts here

**Comment by vogdb** [comment]
@tomaszdurka please look

**Comment by tomaszdurka** [comment]
Looks good for me.

**Pull request merged**
