### PR TITLE
Rename apiKey to serverKey

### PR DESCRIPTION
**Pull request by fvovan**
Unified with CM part

### CODE REVIEW

**Comment by fvovan** [comment]
@tomaszdurka please review. 
I found that config validation is not enough because empty value can be passed to HttpServer constructor by accident. Added a checking for it

**Comment by tomaszdurka** [comment]
Didn't you miss config usage here https://github.com/fvovan/cm-janus/blob/issue-21/lib/cm-api-client.js?

**Comment by fvovan** [comment]
true, my mistake. It's fixed

**Comment by tomaszdurka** [comment]
Looks good.

**Pull request merged**
