### PR TITLE
Verify if cleanup is done when "audioroom" is destroyed

### PR DESCRIPTION
**Pull request by vogdb**
@tomaszdurka @vogdb @njam 

We should make sure that `cm-janus` is aware of room destroy event. If room is destroyed of any reason e.g. master session expires then Janus removes room and notify all connected sessions to the audioroom plugin. It sends something like this:
```
{
   "janus": "event",
   "session_id": 1389549831,
   "sender": 2462998037,
   "plugindata": {
      "plugin": "janus.plugin.cm.audioroom",
      "data": {
         "audioroom": "destroyed",
         "id": "1234"
      }
   }
}
``` 

We should make sure to remove `stream` in `CM` then with e.g. `rpc_removeStream`?

@tomaszdurka can you confirm it is implemented?

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please look

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
looks good

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by vogdb** [comment]
My notes:
 - Remove plugin name field.
 - remove `channels.remove.restore()`

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Looks good!

**Pull request merged**
