### PR TITLE
Add fluentd to VM

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka @vogdb please review

Fluentd is now running in the VM.
You can then send log records to it with https://github.com/fluent/fluent-logger-node
They will show up in a file `/tmp/fluentd-output.log*`.

**Comment by vogdb** [comment]
ok. Why do we configure `fluentd::config::match`?

**Comment by njam** [comment]
The match's pattern is compared against the records' "tag". In this case ("**") all records will match, and they will be stored in this file `/tmp/fluentd-output.log*` - for us to debug.

Should I merge this? or you want to continue on this branch?

**Comment by vogdb** [comment]
Nope. That's fine. lgtm )

**Pull request merged**
