### PR TITLE
Error: Cannot find module 'rimraf'

### PR DESCRIPTION
**Pull request by fvovan**
New cm-janus version fails with this on production:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/cm-janus/lib/job/manager.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/cm-janus/lib/index.js:12:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/cm-janus/bin/cm-janus:4:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

@tomaszdurka @vogdb

### CODE REVIEW

**Comment by fvovan** [comment]
@njam please review

**Comment by njam** [comment]
lgtm, thanks!

**Comment by njam** [comment]
can you bump the version, merge and release?

**Comment by fvovan** [comment]
all except release .
do I have permissions to it? I was trying to release 0.2.0 when error occured.
I run `npm add-user` and put `fvovan` as username but it said `You do not have permission to publish 'cm-janus'. Are you logged in as the correct user? : cm-janus`

**Pull request merged**
