### PR TITLE
Clean up exception log levels

### PR DESCRIPTION
**Pull request by vogdb**
- **warning**: Problems that can appear from time to time, like communication with external services. Their overall volume should be observed to detect anomalies.
- **error**: Problems that should not usually happen. They should be investigated case-by-case.
- **fatal**: Things that should never happen, but for some reason did, and were catched with a global exception handler. These are bugs and should be fixed.

### CODE REVIEW

**Comment by vogdb** [comment]
@njam that is all that I could find and make lower.
@tomaszdurka please review.

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Do they actually occur? If not I would keep them as errors, wdyt @vogdb ?

**Comment by vogdb** [comment]
Well. I never saw them in the logs. It seemed to me that they fit for `warn` level. If you are fine with them as errors then it's fine for me too.

**Pull request closed without merging**
