### PR TITLE
Make sure proxy doesn't crash on invalid json from websocket

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Review done in #155

**Comment by vogdb** [comment]
@tomaszdurka please review. I still use `JanusError.Warning` cause I don't want to close connection on invalid JSON message. Please remember that we have a single error handler which shuts connection for `error instanceof JanusError.Fatal || !(error instanceof JanusError.Error)`

**Comment by tomaszdurka** [comment]
I think especially in terms of extracting client (#162) we should not use Janus errors here. I think it's nothing bad in closing connection on invalid json. It's definitely not expected behaviour from client.

**Comment by tomaszdurka** [comment]
On the other hand it's not "error" in terms of cm-janus application.

What about having custom WebSocket error (or there is already?) and intercept it separately?

**Comment by vogdb** [comment]
@tomaszdurka please look

**Pull request merged**
