### PR TITLE
Add cm-binary path to config

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review

This will be used by job-managers. I add this to include this already in our puppet manifests.

**Comment by vogdb** [comment]
lgtm

**Comment by vogdb** [comment]
hmm, should not we merge those `cm` properties?

**Comment by vogdb** [comment]
like `cmApi`, `cmApplication`?

**Comment by tomaszdurka** [comment]
Let's leave for now. Depends what kind of separation we want in config.
- CM application is about local application.
- CM api about remote machine.

Let's leave separate - we can merge anytime.

**Pull request merged**
