### PR TITLE
Introduce JanusCluster service for redirection

### PR DESCRIPTION
**Pull request by tomaszdurka**
- Introduce JanusCluster service (http client for http://github.com/cargomedia/janus-cluster)
- Use ClusterManager service (if provided) to redirect `/edge` endpoint
- Use origin address for non-edge endpoint

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Please adjust according to https://github.com/njam/janus-cluster/blob/b1702068177fc8cf674978405e9569ff8167ef83/README.md#get-edge-server

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by njam** [comment]
@tomaszdurka @vogdb what's the status here?

**Comment by vogdb** [comment]
Well. I've pulled upstream. The rest is up to @tomaszdurka

**Comment by njam** [comment]
Closing janus-cluster related tickets for the moment

**Pull request closed without merging**
