### PR TITLE
Add simple unit test for service-locator

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
@vogdb please review.
I tried to do impletend calls counter via sinon's spies, but don't know why it didn't work  for me (spy was not attached).

**Comment by vogdb** [comment]
- lets be consistent with names. Somewhere you cut names, somewhere don't. Lets not cut them at all. For example, `funKey` and `funVal`.
- Why there is a second arg in calls `serviceLocator.get(funKey, serviceFunction)` ? ServiceLocator.get doesn't have only one arg? `ServiceLocator.prototype.get = function(name) {`?

**Comment by fvovan** [comment]
@vogdb please review

**Comment by vogdb** [comment]
- lets use `assert(serviceSpy.calledOnce);` instead of callCount
- You are right. `after` is redundant. Let tests to clean themselves manually. In that case we can also move variables from closure scope into the tests itself.

**Comment by fvovan** [comment]
I moved cleaning to end of `it` block

**Comment by vogdb** [comment]
looks very good to me!

**Pull request merged**
