### PR TITLE
Fix PluginStreaming.removeStream

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Not sure about this.

I think it will fix async processor - will not have non-promise to call `.then` on, but the `removeStream` promise will never fulfil. I guess you need something more like:

```js
PluginStreaming.prototype.removeStream = function() {
  var plugin = this;
  return (new Promise(function(resolve, reject) {
    plugin.queue.push(function() {
      if (!plugin.stream) {
        return Promise.resolve();
      }
      return serviceLocator.get('streams').remove(plugin.stream);
    }, function(err) {
        plugin.stream = null;
        if (err) reject(err) else resolve();
    });
  }));
};
```

**Comment by tomaszdurka** [comment]
Or to be aligned with previous version and other usages:
```js
PluginStreaming.prototype.removeStream = function() {
  var plugin = this;
  return (new Promise(function(resolve, reject) {
    plugin.queue.push(function() {
      var promise;
      if (!plugin.stream) {
        promise = Promise.resolve();
      } else {
        promise = serviceLocator.get('streams').remove(plugin.stream);
      }
      return promise.then(resolve, reject);
    });
  }));
};
```

**Comment by vogdb** [comment]
@tomaszdurka please look

**Comment by tomaszdurka** [comment]
lgtm

**Pull request merged**
