### PR TITLE
Do not trigger errors on nonexistent plugins/sessions

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review

Fixes https://github.com/cargomedia/cm-janus/issues/109

**Comment by vogdb** [comment]
This is a huge security hole IMO cause client can send a message for session/plugin which he does not own and do whatever he wants. But I hope that I'm wrong :)

lgtm

**Comment by tomaszdurka** [comment]
Let's go with this solution for now @vogdb and let janus deal with it.

**Comment by vogdb** [comment]
ok ok

**Comment by vogdb** [comment]
you can merge

**Pull request merged**
