### PR TITLE
Use janus uid as cm media id

### PR DESCRIPTION
**Pull request by tomaszdurka**
Semi-depends on https://github.com/cargomedia/cm/issues/2039

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
ok, starting

**Comment by vogdb** [comment]
- PluginAudio. onCreate || onJoin. Why do we create every time Channel and Stream?

- PluginVideo.onSwitch removes stream only on transaction response. PluginAudio.onChangeroom immediately. Why?

- plugin/audio.js. console.log('start'), console.log('mid');

**Comment by tomaszdurka** [comment]
@vogdb please review (sorry for commit mess!)

**Comment by vogdb** [comment]
- Shouldn't we use 'stream/next' stream definition for Audio?

**Comment by tomaszdurka** [comment]
Noes, this is as is in plugins docu (double-checked with Chris).

To be sure, check:
- https://github.com/cargomedia/janus-gateway-rtpbroadcast
- https://github.com/cargomedia/janus-gateway-audioroom

**Comment by tomaszdurka** [comment]
Thanks for streamline :)

**Comment by vogdb** [comment]
lgtm

**Comment by tomaszdurka** [comment]
@vogdb last addition or rather deletion.

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
