### PR TITLE
ProxyConnection StopStream - use http instead of ws

### PR DESCRIPTION
**Pull request by tomaszdurka**
According to API use:
```
curl http://127.0.0.1:8300/janus/[session-id]/[plugin-id] -H "Content-Type: application/json" -X POST -d '{"janus": "detach", "transaction": "[transaction-id]"}'
```

Store session-id and plugin-id on Stream instance only (no need for instances).

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
Looks very good. Two notes:
- Unused dependency in `test/spec/http-server.js` is underscore
- One feature that I forgot to mention before in `janus-http-client`. `stopStream` can receive an `ack` response instead of immediate `success` response. That means your request is acknowledged and stream is not actually stopped. Should we consider this situation in our client?

**Comment by vogdb** [comment]
And I think you see that tests failed.

**Comment by vogdb** [comment]
@tomaszdurka ping me if you need help here

**Comment by tomaszdurka** [comment]
@vogdb I agree it might be important to be sure stream has really stopped. Btw maybe we should even detach whole plugin. Let's move this into new issue and investigate soon. I would be up for merging this and working on structuring janus resources bit more.

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
