### PR TITLE
Job handler: Error: stderr maxBuffer exceeded.

### PR DESCRIPTION
**Pull request by vogdb**
```
2016-01-22 14:35:18.235 ERROR - Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:806:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:540:20)
```

@tomaszdurka @vogdb will this abort the job? if so, then let's find a way to handle it more gracefully.

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
- So there is no need to adjust job handlers as they have been using first arg only anyway?
- We should probably rename `_exec` to `_spawn` in all cases
- I am not fan of stubbing spawn the way we do:
  - Spawns actually returns event emitter, what about simply stubbing spawn with EventEmitter instance and manually trigger events on it in tests? Would simplify tests a lot.
  - Also thought about using something which has simpler interface, but is tested. What about https://www.npmjs.com/package/child-process-promise?

**Comment by vogdb** [comment]
@tomaszdurka please look

**Comment by tomaszdurka** [comment]
lg!

**Pull request merged**
