### PR TITLE
Introduce Channel class

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Depends on #124

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
- tests for Channels.
- Why not 

  ```js
  Channels.prototype.add = function(channel) {
    if (this.contains(channel)) {
      throw new Error('Channel with name `' + channel.name + '` already exists');
    }
    this.list[key] = channel;
  };
  ```
- `spec/streaming.js`. Why recreate `plugin.stream` with a new stream?

  ```js
      var channel = {name: 'channel-name', data: 'channel-data'};
      var stream = new Stream('stream-id', channel);
      plugin.stream = new Stream('stream-id', 'channel-name', 'channel-data', plugin);
  ```

**Comment by tomaszdurka** [comment]
@vogdb 

- Will add
- I check that either channel name or key is there.
- That's mistake

**Comment by vogdb** [comment]
> - I check that either channel name or key is there.

Why to concatenate them then for unique key? If any of them is unique then we can just use `id` for example.

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
- Channels.prototype.findByName can be simplefied through `this.list[channel.name]`?
 - Does it make sense to have `PluginStreaming.prototype.onCreate` if we have `PluginAudio.prototype.onCreate` that is independent of its parent?
 - Should we register `serviceLocator.register('channels', channels)` in `index.js`?

**Comment by tomaszdurka** [comment]
- Let's keep it as is. Maybe key will change from name one day, it's bit more clear and almost same performant.
- Oh there is some bug here. I think it was to be moved to `VideoPlugin` and we moved without changing the name of class :panda_face: Ah, but it's only processed in Video plugin. Messy/hacky/bug. In the end we should have 2 separate onCreate handlers for Video as is, for Audio without publish part.
- Oh yeah! :)

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
Hoooray! lgtm

**Pull request merged**
