### PR TITLE
Subscribe expects channel_data (pass it to cm)

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
Actually storing channel info was already implemented here yesterday but got stuck with testing things together.
reverted.
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Indeed, we did not adjust subscribe method in #108.

Looks good. Merging.

**Comment by tomaszdurka** [comment]
@fvovan please release new version of cm-janus. Please let me know if you need some guidance.

**Comment by fvovan** [comment]
0.2.0 is added. should I deliver it to repo or is it done automatically as well as for CM?

**Pull request merged**
