### PR TITLE
Implement rtpbroadcast thumbnail job handler

### PR DESCRIPTION
**Pull request by tomaszdurka**
Receives data:
```json
{
    "data": {
        "id": "Ababagalamaga",
        "thumb": "/tmp/recordings/thum-Ababagalamaga-12168343410-thumb.mjr"
    },
    "plugin": "janus.plugin.cm.rtpbroadcast",
    "event": "thumbnailing-finished"
}
```

Steps:
- create thumbnail out of 10 seconds `video` => `jpg file`
  - run `janus-pp-rec` to convert `mjr` file into `webm`
- run `cm media-streams import-video-thumbnail {streamChannelId} {jpg file}`
- optional cleanup

command to generate png from webm
```
gst-launch-1.0 filesrc location=video.webm ! decodebin ! videoconvert ! pngenc snapshot=true ! filesink location=frames/snapshot.png
```

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review (after #64, #65)

@kris-lab please review too. There is definetely bug in `janus-pp-rec` - not even sure if ther is command like that. I've only found information about `janus-pp-rec.c`...

**Comment by fvovan** [comment]
@tomaszdurka please merge upstream

**Comment by tomaszdurka** [comment]
@fvovan please review

**Comment by fvovan** [comment]
lgtm

**Comment by tomaszdurka** [comment]
Yes. This possibly needs tests too :)

**Comment by tomaszdurka** [comment]
@kris-lab can you give some details about `janus-pp-rec` command? Thanks.

**Comment by kris-lab** [comment]
- we should make this bin configurable e.g. `/opt/janus/bin/janus-pp-rec` (we will install it there)
- command to run is `janus-pp-rec input.mjr output.webm` - as we know what is the input file from `jobfile` then we can automatically add extension to output: `webm` for video and `opus` for audio. `janus-pp-rec` will detect RTP packet in MJR file and will do conversion for video or audio.

Do you need anything else?

**Comment by kris-lab** [comment]
```
root@debian-7-amd64-default:/home/vagrant# /opt/janus/bin/janus-pp-rec 
Usage: /opt/janus/bin/janus-pp-rec source.mjr destination.[opus|webm]
       /opt/janus/bin/janus-pp-rec --header source.mjr
```

**Comment by kris-lab** [comment]
Audio example:
````bash
root@debian-7-amd64-default:/home/vagrant# /opt/janus/bin/janus-pp-rec /tmp/recordings/rec-rndmvr-studio-agent-bulldog1448299593000-232425849694-audio.mjr audio.opus
/tmp/recordings/rec-rndmvr-studio-agent-bulldog1448299593000-232425849694-audio.mjr --> audio.opus
File is 78736 bytes
Pre-parsing file to generate ordered index...
[WARN] New .mjr header format
This is an audio recording:
  -- Codec:   opus
  -- Created: 1448299593919454
  -- Written: 1448299594280069
Counted 90 RTP packets
Counted 90 frame packets
Writing .opus file header
audio.opus is 76610 bytes
Bye!
```

Video example:
```bash
root@debian-7-amd64-default:/home/vagrant# /opt/janus/bin/janus-pp-rec /tmp/recordings/rec-rndmvr-studio-agent-bulldog1448299593000-232425849810-video.mjr video.webm
/tmp/recordings/rec-rndmvr-studio-agent-bulldog1448299593000-232425849810-video.mjr --> video.webm
File is 8142 bytes
Pre-parsing file to generate ordered index...
[WARN] New .mjr header format
This is a video recording:
  -- Codec:   vp8
  -- Created: 1448299593919561
  -- Written: 1448299594280090
Counted 112 RTP packets
Counted 112 frame packets
  -- 0x0 (fps [960,960] ~ 93)
[WARN] No key frame?? assuming 640x480...
[webm @ 0xa1f4a0] Codec for stream 0 does not use global headers but container format requires global headers
video.webm is 6602 bytes
Bye!
```

**Comment by kris-lab** [comment]
I think we would have to use `ffmpeg` for now... as long as not working with `Gstreamer`

@tomaszdurka wdyt to introduce intermediate script which would run multiple steps to convert files. It would be easier for `cm-janus`. Also when `gstreamer` pipeline is working it will be easier to adjust? No changes for `cm-janus`? Could be installed with puppet maybe?

(copied from [janus](https://groups.google.com/forum/?pli=1#!topic/meetecho-janus/c8_JrDKu_w8))
```
bash
#!/bin/bash
#
# Copyright (c) 2015 Me
# Rev: PA1
# Convert local Janus .mjr files (audio and video) to an .webm file
# containing video and 2ch audio (vp8 + opus)
#
# dependencies:
#    janus-pp-rec (Janus postprocessing) must have been compiled and installed
#    ffmpeg (2015->) must have been installed.
#    (static versions for download exist on the internet)
#
# input is:
# mjr2webm -v myvideo.mjr -a myaudio.mjr out.webm
myhelp () {
    echo $0
    echo 'Usage: mjr2webm -v videofile -a audiofile [outputfile]'
    echo '   "videofile" must be a .mjr video file output from Janus'
    echo '   "audiofile" must be a .mjr audio file output from Janus'
    echo '   "outputfile", if not specified, is "default.webm"'
    echo '   if specified, it must end with filetype ".webm"'
}

video=-v
audio=-a
out=default.webm

if test $# -eq 0; then
   myhelp
   exit 0
fi

if ! which ffmpeg > /dev/null; then
   if ! which ./ffmpeg > /dev/null; then
     echo "Aborting: No 'ffmpeg' found" 1>&2
     exit 1
   else
      ffmpeg=./ffmpeg
   fi
else
   ffmpeg=ffmpeg
fi

if ! which janus-pp-rec > /dev/null; then
     echo "Aborting: No 'janus-pp-rec' found" 1>&2
     exit 1
fi

while test $# -gt 0
do
  case $1 in

  # Normal option processing
    -h | --help)
      # usage and help
      myhelp
      exit 0
      break
      ;;
    -v | --video)
      shift
      video=$1
      ;;
    -a | --audio)
      shift
      audio=$1
      ;;
  # ...
  # Done with options
    *)
      break
      ;;
  esac

  # for testing purposes:
  echo "param $1"

  shift
done


if ! [ -f $video ]; then
   echo "Videofile $video does not exist"
   exit 1
else
   if ! [[ "$video" == *.mjr ]]; then
      echo "Video file must end with .mjr"
      exit 1
   fi
fi
if ! [ -f $audio ]; then
   echo "Audio $audio does not exist"
   exit 1
else
   if ! [[ "$audio" == *.mjr ]]; then
      echo "Video file must end with .mjr"janus-pp-rec
      exit 1janus-pp-rec
   fi
fi
if [ -z "$1" ]; then
    echo "Using default.webm as output file"
else
    out=$1
    if ! [[ "$out" == *.webm ]]; then
       echo "Output file must end with .webm"
       exit 1
    fi
fi

# make temp files
TFILE="$$"
opus=$TFILE.opus
webm=$TFILE.webm

# convert audio to opus
janus-pp-rec $audio $opus

# convert video to webm
janus-pp-rec $video $webm

# mix the two:
# file gets large with high fr.
# by re-coding it we loose quality but reduce the bitrate to 1/4
# however, takes quite some time...
$ffmpeg -i $webm -i $opus -c:v libvpx -b:v 500k -c:a libopus -b:a 64k -r 25 $out

# fast modus
#$ffmpeg -i $webm -i $opus -c:v copy -c:a copy $out

# remove temp files
rm $opus
rm $webm
# done
echo "done!"
#------- end

```

**Comment by tomaszdurka** [comment]
@fvovan please review

**Comment by fvovan** [comment]
lgtm

**Pull request merged**
