### PR TITLE
Verify if cleanup is done when "mountpoint" is destroyed

### PR DESCRIPTION
**Pull request by tomaszdurka**
@tomaszdurka @vogdb @njam

We should make sure that `cm-janus` is aware of `mountpoint` destroy event. If `mountpoint` is destroyed of any reason e.g. master session expires then Janus removes `mountpoint` and notify all connected sessions to the `rtpbroadcast` plugin. It sends following messages:

```
{
   "janus": "event",
   "session_id": 1734302109,
   "sender": 2805623492,
   "plugindata": {
      "plugin": "janus.plugin.cm.rtpbroadcast",
      "data": {
         "streaming": "event",
         "result": {
            "status": "stopped"
         }
      }
   }
}
```
and
```
{
   "janus": "hangup",
   "session_id": 1734302109,
   "sender": 2805623492,
   "reason": "DTLS alert"
}
```

We should make sure to remove `stream` in `CM` then with e.g. `rpc_removeStream`?

@tomaszdurka can you confirm it is implemented?

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by tomaszdurka** [comment]
@vogdb you can also adjust this to your newer switch-case style.

**Comment by vogdb** [comment]
I would use `_.isMatch` instead of `_.isEqual` and also added some tests. Do you want me to do it?

**Comment by vogdb** [comment]
Seems lgtm. @tomaszdurka ?

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Looks good!

**Pull request merged**
