### PR TITLE
Return back JobManager tests

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@fvovan please review ASAP please

**Comment by fvovan** [comment]
I would add cleanup after tests to delete all temp directories

**Comment by fvovan** [comment]
the rest is fine

**Comment by vogdb** [comment]
but currently the created `tmpDirPath` is deleted at the end of the test where it was created.

**Comment by fvovan** [comment]
even if is was failed?

**Comment by vogdb** [comment]
@fvovan please review

**Comment by fvovan** [comment]
lgtm

**Pull request merged**
