### PR TITLE
make Logger to be a class

### PR DESCRIPTION
**Pull request by fvovan**
Possibly try to wrap existing code with new created class and delegate all used methods to minilog.

### CODE REVIEW

**Comment by fvovan** [comment]
@vogdb please review.

**Comment by vogdb** [comment]
Can we somehow get rid of duplicating of `logger` methods?
Just thinking.
```js
var logger = new Logger(__dirname + '/../' + this.config['logPath'], 'app');
return logger.getLogpipe();
```
```js
Logger.prototype.getLogpipe = function() {
  return this._logger;
};
```
not sure through, you can have your ways

**Comment by fvovan** [comment]
@vogdb please review.
yep I thought about it, downside is we now are binded to minilog as we directly use its methods.

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
